version: '3'

services:
  igniter_php:
    build: ./build/php/
    container_name: test_igniter-php
    expose:
      - 9000
    volumes:
      - ./app/:/var/www/html

  igniter_nginx:
    build: ./build/nginx/
    container_name: test_igniter-nginx
    ports:
      - 8040:80
    depends_on:
      - igniter_php
    volumes:
    - ./app/:/var/www/html
      
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./build/database/my_todo_list.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=test_myapp_user
      - MARIADB_PASSWORD=test_myapp_pswd
      - MARIADB_DATABASE=my_todo_list